-- Phase 4 U2: TicketRequest waitlist model, admin audit trail, and the
-- request→ticket back-link. SQL generated by `prisma migrate diff` so it
-- matches Prisma's conventions exactly (avoids future drift noise).
--
-- The tickets.ticket_request_id FK is ON DELETE SET NULL on purpose: deleting
-- a TicketRequest must never cascade-delete an issued, paid Ticket — the Ticket
-- is the durable artifact, the request is only provenance. The one-open-request
-- partial unique index is Prisma-inexpressible and lands in the NEXT migration
-- (add_ticket_request_partial_unique), which must stay last.

-- CreateEnum
CREATE TYPE "TicketRequestIntent" AS ENUM ('PAID', 'MEMBERSHIP_CLAIM');

-- CreateEnum
CREATE TYPE "TicketRequestStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED_BY_USER', 'EXPIRED');

-- CreateEnum
CREATE TYPE "TicketRequestDecision" AS ENUM ('APPROVE', 'REJECT');

-- AlterTable
ALTER TABLE "tickets" ADD COLUMN     "ticket_request_id" TEXT;

-- CreateTable
CREATE TABLE "ticket_requests" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "ticket_type_id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "intent" "TicketRequestIntent" NOT NULL,
    "status" "TicketRequestStatus" NOT NULL DEFAULT 'PENDING',
    "stripe_checkout_session_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ticket_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ticket_request_audits" (
    "id" TEXT NOT NULL,
    "ticket_request_id" TEXT NOT NULL,
    "admin_user_id" TEXT NOT NULL,
    "decision" "TicketRequestDecision" NOT NULL,
    "cap_at_decision" INTEGER,
    "issued_count_before" INTEGER NOT NULL,
    "issued_count_after" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ticket_request_audits_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ticket_requests_stripe_checkout_session_id_key" ON "ticket_requests"("stripe_checkout_session_id");

-- CreateIndex
CREATE INDEX "ticket_requests_event_id_status_idx" ON "ticket_requests"("event_id", "status");

-- CreateIndex
CREATE INDEX "ticket_requests_user_id_idx" ON "ticket_requests"("user_id");

-- CreateIndex
CREATE INDEX "ticket_request_audits_ticket_request_id_idx" ON "ticket_request_audits"("ticket_request_id");

-- CreateIndex
CREATE UNIQUE INDEX "tickets_ticket_request_id_key" ON "tickets"("ticket_request_id");

-- AddForeignKey
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_ticket_request_id_fkey" FOREIGN KEY ("ticket_request_id") REFERENCES "ticket_requests"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ticket_requests" ADD CONSTRAINT "ticket_requests_ticket_type_id_fkey" FOREIGN KEY ("ticket_type_id") REFERENCES "ticket_types"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ticket_requests" ADD CONSTRAINT "ticket_requests_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE CASCADE;
